version: '2'

services:
  scraper_appointment_finder:
    build: ./docker/scrapy
    env_file:
      - ./.env
    volumes:
       - ./:/scraper
    working_dir: /scraper
    command: bash /scraper/docker/scrapy.sh berlinspider

  scraper_appointment_finder_immigration_office:
      build: ./docker/scrapy
      env_file:
        - ./.env
      volumes:
         - ./:/scraper
      working_dir: /scraper
      command: bash /scraper/docker/scrapy.sh immigrationOffice